### ISSUE TITLE
Refresh button.

### ISSUE THREAD

**Issue by 26-PM** [chinxcode/devArena-leaderboard#1]
It would be helpful to have a refresh button so I can check for updated results without having to manually refresh the page and go through verification again, which is inconvenient.

**Comment by chinxcode** [comment]
I initially provided this feature but had to remove it after experiencing several DDoS attacks on the site. As a preventative measure, I introduced human verification to prevent request flooding and avoid exhausting my 'free-tier' resources.

**Comment by 26-PM** [comment]
several DDos attacks on this site really? Lol

**Comment by chinxcode** [comment]
Yeah, it was a DoS attack by someone who learned a few tricks and thought it’d be fun to mess with the site. I've sorted it out and put some protections in place to stop it from happening again.

**Comment by 26-PM** [comment]
Okay fine so I will require to manually refresh it right.
